name: Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install .
          pip install uvicorn


      - name: Start cachemeifyoucan server
        run: |
          echo -e "github:\n  url: https://raw.githubusercontent.com" > cachemeifyoucan.yaml
          uvicorn cachemeifyoucan:app --host 127.0.0.1 --port 9999 > server.log 2>&1 &
          echo $! > uvicorn.pid
          sleep 5  # Give the server time to start

      - name: Download file via proxy (cache miss)
        run: |
          curl -s -o downloaded1.md http://127.0.0.1:9999/github/derekhiggins/cachemeifyoucan/refs/heads/main/README.md

          #Check cache file created
          CACHE_FILE=$(grep -oP '(?<=Saving response to cache: )[^ ]+' server.log | tail -1)
          if [ -z "$CACHE_FILE" ]; then
            echo "No cache file created"
            exit 1
          fi
          echo "Cache file: $CACHE_FILE"
          test -f "$CACHE_FILE"

      - name: Download file via proxy again (cache hit)
        run: |
          curl -s -o downloaded2.md http://127.0.0.1:9999/github/derekhiggins/cachemeifyoucan/refs/heads/main/README.md
          grep "Getting response from cache" server.log || (echo "No cache hit detected" && exit 1)

          # Check that the 2 files are the same and contain some expected text
          diff downloaded1.md downloaded2.md
          grep -A 5 Usage downloaded1.md

      - name: Info
        if: always()
        run: |
          cat server.log
